In [38]:
import numpy as np
from sklearn.model_selection import train_test_split
from numpy.linalg import norm #(a-b)

In [29]:
data = np.random.randint(0, 50, (10,3))
data

array([[25, 10, 15],
       [17,  4, 14],
       [17, 21, 35],
       [32, 37, 37],
       [17,  1, 15],
       [35, 43,  6],
       [46,  0,  3],
       [41, 22, 20],
       [29,  2, 40],
       [42,  9, 39]])

In [39]:
X_train

array([[29,  2],
       [17, 21],
       [41, 22],
       [32, 37],
       [35, 43],
       [25, 10],
       [42,  9],
       [17,  4]])

In [48]:
y_train

array([40, 35, 20, 37,  6, 15, 39, 14])

In [37]:
X_test

array([[17,  1],
       [46,  0]])

In [54]:
class KNNRegressor:
    
    def __init__(self, k):
        self.k = k
    
    def fit(self, X, y):
        self.X = X
        self.y = y
    
    def predict(self, X_test):
        #given (17,  1) loop thru 
        predictions = []
        for x_test in X_test:
            dist_list = []
            for data_point in self.X:
                dist = norm(x_test - data_point)
                dist_list.append(dist)
            indices = np.argpartition(dist_list, self.k)[:self.k]
            y_train_top = self.y[indices]
            final_prediction = y_train_top.mean()
            predictions.append(final_prediction)
        return predictions
            
    

In [47]:
np.argpartition([3,4,6,2,4.1], 3)[:3]

array([3, 0, 1])

In [41]:
np.array((17,  1)) - np.array((29,  2))

array([-12,  -1])

In [42]:
norm(np.array((17,  1)) - np.array((29,  2)))

12.041594578792296

In [30]:
X = data[:, :2]
y = data[:, -1]

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [36]:
y_test

array([15,  3])

In [52]:
X_test

array([[17,  1],
       [46,  0]])

In [58]:
knn = KNNRegressor(k=3)

In [59]:
knn.fit(X, y)

In [60]:
knn.predict(X_test)

[23.0, 27.333333333333332]