In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')

In [10]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [12]:
X = df.drop(columns="species")
y = df.species

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [16]:
X_train.shape, X_test.shape

((112, 4), (38, 4))

In [17]:
y_train.shape, y_test.shape

((112,), (38,))

In [18]:
X_test.head()

sepal_length  sepal_width  petal_length  petal_width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5          1.5
76            6.8          2.8           4.8          1.4

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')

y = df['species']
X = df[['petal_length', 'petal_width']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [20]:
import numpy as np

In [48]:
data = np.random.randint(0, 50, (5, 3))

In [49]:
data

array([[17, 27, 31],
       [44, 43, 47],
       [31, 16, 11],
       [28, 44, 23],
       [17, 24, 22]])

In [51]:
class KNNClassifier:
    
    def __init__(self, k):
        self.k = k
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
    def predict(self, X_test):
        pass
        
        
        

In [52]:
knn = KNNClassifier(3)

In [53]:
X = data[:, :2]
y= data[:, -1]

In [ ]:
X_test, X_train, y_test, y_train = 

In [54]:
X, y

(array([[17, 27],
        [44, 43],
        [31, 16],
        [28, 44],
        [17, 24]]),
 array([31, 47, 11, 23, 22]))

In [55]:
knn.fit(X, y)